#
# Copyright (C) 2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "signal-crypto"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
aes = { version = "0.8.3", features = ["zeroize"] }
cbc = { version = "0.1.2", features = ["std", "zeroize"] }
ctr = { version = "0.9.2", features = ["zeroize"] }
subtle = "2.3"
ghash = { version = "0.5.0", features = ["zeroize"] }
hmac = { version = "0.12", features = ["reset"] }
sha1 = "0.10"
sha2 = "0.10"
thiserror = "1.0.38"
displaydoc = "0.2"

[dev-dependencies]
criterion = "0.5"
hex = "0.4"
hex-literal = "0.4.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bench]]
name = "aes_gcm"
harness = false
