include = ["Cargo.toml", "rust/**/*.toml"]

[formatting]
reorder_keys = false
indent_string = '    '

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "dev-dependencies", "build-dependencies"]

[rule.formatting]
reorder_keys = true
inline_table_expand = false
