#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge-macros"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2018"
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0" }
syn-mid = "0.5"
unzip3 = "1.0"

[features]
ffi = []
jni = []
node = []
