#
# Copyright (C) 2024 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge-testing"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
attest = { workspace = true }
libsignal-bridge-macros = { workspace = true }
libsignal-bridge-types = { workspace = true }
libsignal-core = { workspace = true }
libsignal-keytrans = { workspace = true }
libsignal-message-backup = { workspace = true, features = ["json"] }
libsignal-net = { workspace = true }
libsignal-protocol = { workspace = true }

const-str = { workspace = true, features = ["std"] }
futures-util = { workspace = true }
hex-literal = { workspace = true }
http = { workspace = true }
nonzero_ext = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
scopeguard = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
uuid = { workspace = true }

jni = { workspace = true, optional = true }
linkme = { workspace = true, optional = true }
neon = { workspace = true, optional = true, default-features = false, features = ["napi-6"] }

[features]
ffi = ["libsignal-bridge-types/ffi"]
jni = ["dep:jni", "libsignal-bridge-types/jni"]
node = ["dep:linkme", "dep:neon", "libsignal-bridge-types/node"]
signal-media = ["libsignal-bridge-types/signal-media"]
