[package]
name = "device-transfer"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[lints]
workspace = true

[dependencies]
boring = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
