[package]
name = "device-transfer"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
boring = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
