#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-jni"
version = "0.30.1"
authors = ["Signal Messenger LLC"]
edition = "2018"
license = "AGPL-3.0-only"

[lib]
name = "signal_jni"
crate-type = ["cdylib"]

[features]
default = ["armv8"]
armv8 = ["libsignal-protocol/armv8", "signal-crypto/armv8"]

[dependencies]
libsignal-protocol = { path = "../../protocol" }
signal-crypto = { path = "../../crypto" }
libsignal-bridge = { path = "../shared", features = ["jni", "signal-media"] }
async-trait = "0.1.41"
cfg-if = "1.0.0"
jni = "0.19"
rand = "0.7.3"
log = "0.4"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }

[target.aarch64-linux-android.dependencies]
cpufeatures = "0.2.2" # Make sure 64-bit Android gets optimized crypto
