#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-jni"
version = "0.8.1"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "AGPL-3.0-only"

[lib]
name = "signal_jni"
crate-type = ["cdylib"]

[dependencies]
libsignal-protocol = { path = "../../protocol" }
signal-crypto = { path = "../../crypto" }
libsignal-bridge = { path = "../shared", features = ["jni"] }
async-trait = "0.1.41"
jni = "0.19"
rand = "0.7.3"
log = "0.4"
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
