#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-jni"
version = "0.1.0"
authors = ["Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "AGPL-3.0-only"

[lib]
name = "signal_jni"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-protocol-rust = { path = "../../protocol" }
aes-gcm-siv = { path = "../../aes-gcm-siv" }
libsignal-bridge = { path = "../shared", features = ["jni"] }
async-trait = "0.1.41"
jni = "0.17"
rand = "0.7.3"
