[package]
name = "libsignal-net"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[dependencies]
attest = { path = "../attest" }
libsignal-core = { path = "../core" }
libsignal-protocol = { path = "../protocol" }
libsignal-svr3 = { path = "../svr3" }

async-trait = "0.1.41"
base64 = "0.21"
bincode = "1.0"
bitstream-io = "1.10.0"
boring = { git = "https://github.com/signalapp/boring", tag = "signal-v4.6.0" }
bytes = "1.4.0"
const-str = { version = "0.5.6", features = ["std"] }
derive-where = "1.2.7"
displaydoc = "0.2"
either = "1.10.0"
futures-util = "0.3.7"
hex = "0.4"
hmac = "0.12"
http = "1.0.0"
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["http2", "client"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
indexmap = "2.1.0"
itertools = "0.12.0"
log = "0.4.19"
nonzero_ext = "0.3.0"
num_enum = "0.6.1"
prost = "0.12.1"
rand = "0.8.0"
rand_core = "0.6"
rustls = { version = "0.23.4", default-features = false, features = ["ring", "std", "tls12"] }
rustls-platform-verifier = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
static_assertions = "1.1"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1", features = ["rt", "time", "macros"] }
tokio-boring = { git = "https://github.com/signalapp/boring", tag = "signal-v4.6.0" }
tokio-stream = "0.1.14"
tokio-tungstenite = { version = "0.21.0" }
tokio-util = "0.7.9"
tungstenite = { version = "0.21.0" }
url = "2.4.1"
uuid = "1.1.2"

[build-dependencies]
prost-build = "0.12.1"

[dev-dependencies]
assert_matches = "1.5.0"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1"
env_logger = "0.10.0"
hex-literal = "0.4.1"
hickory-proto = "0.24.1"
lazy_static = "1.4.0"
proptest = "1.4.0"
proptest-state-machine = "0.1.0"
rcgen = "0.13.0"
snow = "0.9.5"
test-case = "3.3.1"
tls-parser = "0.11.0"
tokio = { version = "1", features = ["test-util", "io-std", "rt-multi-thread"] }
url = "2.4.1"
warp = { version = "0.3.6", features = ["tls"] }
