[package]
name = "libsignal-net-grpc"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[dependencies]
libsignal-core = { workspace = true }

prost = { workspace = true }
tonic = { workspace = true, default-features = false, features = ["codegen"] }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
