#
# Copyright 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "zkgroup"
version = "0.8.2"
authors = ["Trevor Perrin <trevp@signal.org>"]
edition = "2018"
description = "A zero-knowledge group library"
license = "AGPL-3.0-only"

[lib]
name = "zkgroup"
crate-type = [ "staticlib", "cdylib", "rlib"]

[dependencies]
bincode = "1.2.1"
serde = { version = "1.0.106", features = ["derive"] }
sha2 = "0.8.0"
jni = { version = "0.16.0", default-features = false }
hex = "0.4.0"
aead = "0.4.0"
aes-gcm-siv = "0.10.0"

[dependencies.curve25519-dalek]
features = ["std", "serde", "alloc"]
version = "2.0.0"
git = "https://github.com/signalapp/curve25519-dalek.git"
branch = "lizard2"

[dependencies.poksho]
git = "https://github.com/signalapp/poksho.git"
tag = "v0.7.0"

[features]
default = ["u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
u64_backend = ["curve25519-dalek/u64_backend"]
simd_backend = ["curve25519-dalek/simd_backend"]
nightly = ["curve25519-dalek/nightly"]

# Below is for benchmarking:

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "zkgroup_benchmarks"
harness = false
